[package]
name = "ncal"
version = "0.3.0"
edition = "2024"
description = "A terminal Bikram Sambat calendar tool, inspired by Unix cal."
license = "MIT"
authors= ["rajatdahal contact@rajatdahal.com.np"]
readme= "README.md"
repository="https://github.com/razzat008/ncal"
keywords = ["cal","calendar","nepali"]

[dependencies]
chrono = { version = "0.4.44", features = ["serde"] }
clap = { version = "4.6.1", features = ["derive"] }
thiserror = "2.0.18"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
